name: Daily ETL Processing
on:
  schedule:
    - cron: '0 6 * * *' # 6 AM daily PDT
  workflow_dispatch:

jobs:
  etl-processing:
    runs-on: ubuntu-latest
    env:
      NBA_SEASON: '2024-25'
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run ETL Pipeline
        run: |
          python -m pip install -r requirements.txt
          python etl_pipelines/main.py --season $NBA_SEASON
        env:
          NBA_API_KEY: ${{ secrets.NBA_API_KEY }}
          DB_CONN_STRING: ${{ secrets.WAREHOUSE_CONNECTION }}

      - name: Data Quality Tests
        run: pytest tests/data_quality/ -v

      - name: Upload Processed Data
        uses: actions/upload-artifact@v3
        with:
          name: processed-data-${{ github.run_id }}
          path: |
            data_architecture/processed/*.parquet
            data_architecture/processed/*.csv